/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellCalendarioRouteImport } from './routes/_shell/calendario'
import { Route as ShellSemanaRouteImport } from './routes/_shell/semana'
import { Route as ShellTarefasRouteImport } from './routes/_shell/tarefas'
import { Route as ShellEmpresasIndexRouteImport } from './routes/_shell/empresas.index'
import { Route as ShellEmpresasCompanyIdRouteImport } from './routes/_shell/empresas.$companyId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarioRoute = ShellCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSemanaRoute = ShellSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTarefasRoute = ShellTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmpresasIndexRoute = ShellEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEmpresasCompanyIdRoute = ShellEmpresasCompanyIdRouteImport.update({
  id: '/empresas/$companyId',
  path: '/empresas/$companyId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/calendario': typeof ShellCalendarioRoute
  '/semana': typeof ShellSemanaRoute
  '/tarefas': typeof ShellTarefasRoute
  '/empresas/$companyId': typeof ShellEmpresasCompanyIdRoute
  '/empresas/': typeof ShellEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendario': typeof ShellCalendarioRoute
  '/semana': typeof ShellSemanaRoute
  '/tarefas': typeof ShellTarefasRoute
  '/': typeof ShellIndexRoute
  '/empresas/$companyId': typeof ShellEmpresasCompanyIdRoute
  '/empresas': typeof ShellEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/calendario': typeof ShellCalendarioRoute
  '/_shell/semana': typeof ShellSemanaRoute
  '/_shell/tarefas': typeof ShellTarefasRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/empresas/$companyId': typeof ShellEmpresasCompanyIdRoute
  '/_shell/empresas/': typeof ShellEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendario'
    | '/semana'
    | '/tarefas'
    | '/empresas/$companyId'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendario'
    | '/semana'
    | '/tarefas'
    | '/'
    | '/empresas/$companyId'
    | '/empresas'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/calendario'
    | '/_shell/semana'
    | '/_shell/tarefas'
    | '/_shell/'
    | '/_shell/empresas/$companyId'
    | '/_shell/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendario': {
      id: '/_shell/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof ShellCalendarioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/semana': {
      id: '/_shell/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof ShellSemanaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tarefas': {
      id: '/_shell/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof ShellTarefasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/empresas/': {
      id: '/_shell/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof ShellEmpresasIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/empresas/$companyId': {
      id: '/_shell/empresas/$companyId'
      path: '/empresas/$companyId'
      fullPath: '/empresas/$companyId'
      preLoaderRoute: typeof ShellEmpresasCompanyIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCalendarioRoute: typeof ShellCalendarioRoute
  ShellSemanaRoute: typeof ShellSemanaRoute
  ShellTarefasRoute: typeof ShellTarefasRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellEmpresasCompanyIdRoute: typeof ShellEmpresasCompanyIdRoute
  ShellEmpresasIndexRoute: typeof ShellEmpresasIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCalendarioRoute: ShellCalendarioRoute,
  ShellSemanaRoute: ShellSemanaRoute,
  ShellTarefasRoute: ShellTarefasRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellEmpresasCompanyIdRoute: ShellEmpresasCompanyIdRoute,
  ShellEmpresasIndexRoute: ShellEmpresasIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
